services:
  - type: web
    name: test-app-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SECRET_KEY
        sync: false
      - key: INGEST_TOKEN
        generateValue: true
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASS
        sync: false
